# Generated by Django 4.2.16 on 2024-09-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='project',
        ),
    ]
